version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: homelink-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: homelink

  mongo-express:
    image: mongo-express:1.0.2
    container_name: homelink-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo
